### ISSUE TITLE
项目报错咨询：TypeError: module() takes at most 2 arguments (3 given)

### ISSUE THREAD

**Issue by mzy98** [hanruihua/rl_rvo_nav#17]
具体的报错信息如下：
Traceback (most recent call last):
  File "E:\KT_info\rl_rvo_nav\rl_rvo_nav\policy_train\train_process_s1.py", line 98, in <module>
    env = gym.make(args.env_name, world_name=args.world_path, robot_number=args.robot_number, neighbors_region=args.neighbors_region, neighbors_num=args.neighbors_num, robot_init_mode=args.init_mode, env_train=args.env_train, random_bear=args.random_bear, random_radius=args.random_radius, reward_parameter=args.reward_parameter, full=args.full)
  File "E:\Laboratory_project\interpreter\rl_rvo_nav\lib\site-packages\gym\envs\registration.py", line 581, in make
    env_creator = load(spec_.entry_point)
  File "E:\Laboratory_project\interpreter\rl_rvo_nav\lib\site-packages\gym\envs\registration.py", line 61, in load
    mod = importlib.import_module(mod_name)
  File "E:\Software\python-3.8.2\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\KT_info\rl_rvo_nav\gym_env\gym_env\envs\__init__.py", line 1, in <module>
    from gym_env.envs.mrnav import mrnav
  File "E:\KT_info\rl_rvo_nav\gym_env\gym_env\envs\mrnav.py", line 2, in <module>
    from gym_env.envs.ir_gym import ir_gym
  File "E:\KT_info\rl_rvo_nav\gym_env\gym_env\envs\ir_gym.py", line 7, in <module>
    class ir_gym(env_base):
TypeError: module() takes at most 2 arguments (3 given)

**Comment by hanruihua** [comment]
This error should be caused by the gym version. Please try to downgrade the gym version to solve this error.
